task_name: "blender.small"
dir_path: "~/Github/openchat/saved"
batch_size: 8
lr: 5e-7
num_gpus: 0
weight_decay: 1e-4
num_training_step: 200000
num_warmup_step: 0
accumulate_grad_batches: 1
accelerator: "ddp"
precision: 32
max_len: 1024
val_check_interval: 1.0
monitor: "val_loss"
use_early_stopping: True
use_tensor_board: True
optimizer: "Adam"